In [1080]:
import pandas as pd
from sodapy import Socrata

client = Socrata("data.cdc.gov", None)

results = client.get("8pt5-q6wp", limit=3000)

# Convert to pandas DataFrame
df = pd.DataFrame.from_records(results)
df.reset_index(drop=True)


df

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,phase,indicator,group,state,subgroup,time_period,time_period_label,value,lowci,highci,confidence_interval,quartile_range
0,1,Symptoms of Depressive Disorder,National Estimate,United States,United States,1,Apr 23 - May 5,23.5,22.7,24.3,22.7 - 24.3,NaN
1,1,Symptoms of Depressive Disorder,By Age,United States,18 - 29 years,1,Apr 23 - May 5,32.7,30.2,35.2,30.2 - 35.2,NaN
2,1,Symptoms of Depressive Disorder,By Age,United States,30 - 39 years,1,Apr 23 - May 5,25.7,24.1,27.3,24.1 - 27.3,NaN
3,1,Symptoms of Depressive Disorder,By Age,United States,40 - 49 years,1,Apr 23 - May 5,24.8,23.3,26.2,23.3 - 26.2,NaN
4,1,Symptoms of Depressive Disorder,By Age,United States,50 - 59 years,1,Apr 23 - May 5,23.2,21.5,25,21.5 - 25.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2992,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Virginia,Virginia,14,Sep 2 - Sep 14,33.3,30,36.6,30.0 - 36.6,33.2-35.3
2993,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Washington,Washington,14,Sep 2 - Sep 14,35.4,33.3,37.6,33.3 - 37.6,35.4-38.1
2994,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,West Virginia,West Virginia,14,Sep 2 - Sep 14,38.4,33.2,43.7,33.2 - 43.7,38.2-41.7
2995,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Wisconsin,Wisconsin,14,Sep 2 - Sep 14,31.3,27.5,35.2,27.5 - 35.2,26.3-33.1
2996,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Wyoming,Wyoming,14,Sep 2 - Sep 14,33.6,29.6,37.9,29.6 - 37.9,33.2-35.3

In [1081]:
age = df[df['group']=='By Age']
ny = df[df['state']=='New York']
ny1 = df[df['state']=='New York']
ny2 = df[df['state']=='New York']
ny3 = df[df['state']=='New York']
ny4 = df[df['state']=='New York']
ny5 = df[df['state']=='New York']
ny6 = df[df['state']=='New York']
ny.reset_index(drop=True, inplace=True)
ny1.reset_index(drop=True, inplace=True)
ny2.reset_index(drop=True, inplace=True)
ny3.reset_index(drop=True, inplace=True)
ny4.reset_index(drop=True, inplace=True)
ny5.reset_index(drop=True, inplace=True)
ny6.reset_index(drop=True, inplace=True)

#combined = pd.concat([age,ny])
ageRange = ['18 - 29 years', '30 - 39 years', '40 - 49 years', '50 - 59 years', '60 - 69 years', '70 - 79 years', '80 years and above']
ny['age'] = ageRange[0]
ny1['age'] = ageRange[1]
ny2['age'] = ageRange[2]
ny3['age'] = ageRange[3]
ny4['age'] = ageRange[4]
ny5['age'] = ageRange[5]
ny6['age'] = ageRange[6]


ny6

c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,phase,indicator,group,state,subgroup,time_period,time_period_label,value,lowci,highci,confidence_interval,quartile_range,age
0,1,Symptoms of Depressive Disorder,By State,New York,New York,1,Apr 23 - May 5,28.7,24.6,33.1,24.6 - 33.1,24.1 - 28.7,80 years and above
1,1,Symptoms of Anxiety Disorder,By State,New York,New York,1,Apr 23 - May 5,36.1,32.1,40.2,32.1 - 40.2,31.7 - 37.0,80 years and above
2,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,1,Apr 23 - May 5,41.4,36.7,46.1,36.7 - 46.1,36.8 - 41.4,80 years and above
3,1,Symptoms of Depressive Disorder,By State,New York,New York,2,May 7 - May 12,29.2,24.2,34.6,24.2 - 34.6,25.7 - 35.5,80 years and above
4,1,Symptoms of Anxiety Disorder,By State,New York,New York,2,May 7 - May 12,33,27.7,38.5,27.7 - 38.5,31.6 - 38.3,80 years and above
5,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,2,May 7 - May 12,36.9,31.6,42.4,31.6 - 42.4,36.1 - 48.4,80 years and above
6,1,Symptoms of Depressive Disorder,By State,New York,New York,3,May 14 - May 19,23.8,20,28,20.0 - 28.0,23.3-25.6,80 years and above
7,1,Symptoms of Anxiety Disorder,By State,New York,New York,3,May 14 - May 19,26.8,23.1,30.8,23.1 - 30.8,25.3-27.4,80 years and above
8,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,3,May 14 - May 19,34.9,30.5,39.5,30.5 - 39.5,32.6-34.9,80 years and above
9,1,Symptoms of Depressive Disorder,By State,New York,New York,4,May 21 - May 26,23.7,20,27.8,20.0 - 27.8,23.0-25.8,80 years and above
10,1,Symptoms of Anxiety Disorder,By State,New York,New York,4,May 21 - May 26,30.6,26.8,34.5,26.8 - 34.5,28.7-30.6,80 years and above
11,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,4,May 21 - May 26,34.4,30.5,38.5,30.5 - 38.5,33.2-35.5,80 years and above
12,1,Symptoms of Depressive Disorder,By State,New York,New York,5,May 28 - June 2,24.5,21.3,27.9,21.3 - 27.9,24.4-26.8,80 years and above
13,1,Symptoms of Anxiety Disorder,By State,New York,New York,5,May 28 - June 2,29.8,26.4,33.4,26.4 - 33.4,29.7-31.7,80 years and above
14,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,5,May 28 - June 2,34.8,31.6,38.2,31.6 - 38.2,34.3-36.9,80 years and above
15,1,Symptoms of Depressive Disorder,By State,New York,New York,6,June 4 - June 9,28.5,24,33.2,24.0 - 33.2,27.3-30.3,80 years and above
16,1,Symptoms of Anxiety Disorder,By State,New York,New York,6,June 4 - June 9,36.3,30.9,41.9,30.9 - 41.9,32.8-36.3,80 years and above
17,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,6,June 4 - June 9,38.6,33.2,44.2,33.2 - 44.2,37.7-40.7,80 years and above
18,1,Symptoms of Depressive Disorder,By State,New York,New York,7,June 11 - June 16,23.4,19.6,27.5,19.6 - 27.5,21.8-23.9,80 years and above
19,1,Symptoms of Anxiety Disorder,By State,New York,New York,7,June 11 - June 16,28.7,24.3,33.3,24.3 - 33.3,27.4-30.5,80 years and above
20,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,7,June 11 - June 16,32.9,28.1,37.8,28.1 - 37.8,32.3-34.9,80 years and above
21,1,Symptoms of Depressive Disorder,By State,New York,New York,8,June 18 - June 23,24.2,20.8,27.9,20.8 - 27.9,22.5-25.0,80 years and above
22,1,Symptoms of Anxiety Disorder,By State,New York,New York,8,June 18 - June 23,26.9,23.6,30.5,23.6 - 30.5,21.3-27.7,80 years and above
23,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,8,June 18 - June 23,32.9,29.4,36.7,29.4 - 36.7,31.8-34.4,80 years and above
24,1,Symptoms of Depressive Disorder,By State,New York,New York,9,June 25 - June 30,23.9,20.6,27.4,20.6 - 27.4,23.9-26.0,80 years and above
25,1,Symptoms of Anxiety Disorder,By State,New York,New York,9,June 25 - June 30,30.6,27,34.4,27.0 - 34.4,29.5-32.2,80 years and above
26,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,9,June 25 - June 30,34.3,30.5,38.3,30.5 - 38.3,34.1-35.9,80 years and above
27,1,Symptoms of Depressive Disorder,By State,New York,New York,10,July 2 - July 7,28.5,25,32.1,25.0 - 32.1,26.8-29.3,80 years and above
28,1,Symptoms of Anxiety Disorder,By State,New York,New York,10,July 2 - July 7,34.7,30.4,39.2,30.4 - 39.2,33.0-35.3,80 years and above
29,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,10,July 2 - July 7,39.7,35.4,44,35.4 - 44.0,38.1-40.6,80 years and above
30,1,Symptoms of Depressive Disorder,By State,New York,New York,11,July 9 - July 14,25,21.1,29.1,21.1 - 29.1,24.1-27.2,80 years and above
31,1,Symptoms of Anxiety Disorder,By State,New York,New York,11,July 9 - July 14,34.2,29.2,39.6,29.2 - 39.6,31.1-34.2,80 years and above
32,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,11,July 9 - July 14,38.3,33.4,43.5,33.4 - 43.5,34.8-38.3,80 years and above
33,1,Symptoms of Depressive Disorder,By State,New York,New York,12,July 16 - July 21,29.3,25.1,33.8,25.1 - 33.8,26.0-29.3,80 years and above
34,1,Symptoms of Anxiety Disorder,By State,New York,New York,12,July 16 - July 21,36.2,31.6,41.1,31.6 - 41.1,35.6-38.4,80 years and above
35,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,12,July 16 - July 21,41.1,36,46.4,36.0 - 46.4,40.6-43.5,80 years and above
36,2,Symptoms of Depressive Disorder,By State,New York,New York,13,Aug 19 - Aug 31,22.5,19.7,25.4,19.7 - 25.4,21.0-23.8,80 years and above
37,2,Symptoms of Anxiety Disorder,By State,New York,New York,13,Aug 19 - Aug 31,29.9,26.9,33.1,26.9 - 33.1,28.5-30.6,80 years and above
38,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,13,Aug 19 - Aug 31,34.4,31.3,37.6,31.3 - 37.6,33.3-35.6,80 years and above
39,2,Symptoms of Depressive Disorder,By State,New York,New York,14,Sep 2 - Sep 14,25.1,21.6,28.8,21.6 - 28.8,23.3-26.5,80 years and above
40,2,Symptoms of Anxiety Disorder,By State,New York,New York,14,Sep 2 - Sep 14,33.5,29.7,37.5,29.7 - 37.5,33.5-36.9,80 years and above
41,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,14,Sep 2 - Sep 14,37.7,33.6,41.9,33.6 - 41.9,35.4-38.1,80 years and above

In [1082]:
new_york = pd.concat([ ny, ny1, ny2, ny3, ny4, ny5, ny6])
new_york.to_csv('NY_MENTAL_HEALTH_ONLY.csv', index=False)

In [1083]:
new_york

,phase,indicator,group,state,subgroup,time_period,time_period_label,value,lowci,highci,confidence_interval,quartile_range,age
0,1,Symptoms of Depressive Disorder,By State,New York,New York,1,Apr 23 - May 5,28.7,24.6,33.1,24.6 - 33.1,24.1 - 28.7,18 - 29 years
1,1,Symptoms of Anxiety Disorder,By State,New York,New York,1,Apr 23 - May 5,36.1,32.1,40.2,32.1 - 40.2,31.7 - 37.0,18 - 29 years
2,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,1,Apr 23 - May 5,41.4,36.7,46.1,36.7 - 46.1,36.8 - 41.4,18 - 29 years
3,1,Symptoms of Depressive Disorder,By State,New York,New York,2,May 7 - May 12,29.2,24.2,34.6,24.2 - 34.6,25.7 - 35.5,18 - 29 years
4,1,Symptoms of Anxiety Disorder,By State,New York,New York,2,May 7 - May 12,33,27.7,38.5,27.7 - 38.5,31.6 - 38.3,18 - 29 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,2,Symptoms of Anxiety Disorder,By State,New York,New York,13,Aug 19 - Aug 31,29.9,26.9,33.1,26.9 - 33.1,28.5-30.6,80 years and above
38,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,13,Aug 19 - Aug 31,34.4,31.3,37.6,31.3 - 37.6,33.3-35.6,80 years and above
39,2,Symptoms of Depressive Disorder,By State,New York,New York,14,Sep 2 - Sep 14,25.1,21.6,28.8,21.6 - 28.8,23.3-26.5,80 years and above
40,2,Symptoms of Anxiety Disorder,By State,New York,New York,14,Sep 2 - Sep 14,33.5,29.7,37.5,29.7 - 37.5,33.5-36.9,80 years and above
41,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,14,Sep 2 - Sep 14,37.7,33.6,41.9,33.6 - 41.9,35.4-38.1,80 years and above

In [1084]:
april23 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/93c29d8395f89d5d0eff39e1a9dcba69c820b33f/by-age.csv?raw=True",index_col=0)
april23['date'] = '04-23-2020'
april23['period'] = 1
april23 = april23.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1085]:
april24 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/8f4cd591c65b11c23bc3ebae25f523df5da6ceb6/by-age.csv?raw=True",index_col=0)
april24['date'] = '04-24-2020'
april24['period'] = 1
april24 = april24.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1086]:
april25 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/4bc53684bcae8ecaede11197d5f01c2d4c5f956a/by-age.csv?raw=True",index_col=0)
april25['date'] = '04-25-2020'
april25['period'] = 1
april25 = april25.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1087]:
april26 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/da609d813e5a53dd8402ad018bc2a2d1ea7e3170/by-age.csv?raw=True",index_col=0)
april26['date'] = '04-26-2020'
april26['period'] = 1
april26 = april26.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1088]:
april27 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/3ec3fa97d44c5b3054477c9c0998fa6d466bca72/by-age.csv?raw=True",index_col=0)
april27['date'] = '04-27-2020'
april27['period'] = 1
april27 = april27.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1089]:
april28 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/81fcf12be08aadd730d1d39c153e3fd9ab371e77/by-age.csv?raw=True",index_col=0)
april28['date'] = '04-28-2020'
april28['period'] = 1
april28 = april28.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1090]:
april29 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/c68db06972c3100297a615ba397245eff8b3ee9f/by-age.csv?raw=True",index_col=0)
april29['date'] = '04-29-2020'
april29['period'] = 1
april29 = april29.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1091]:
april30 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/cdc5866a09ad9fa3d2c8e449dcf1803775b0a6df/by-age.csv?raw=True",index_col=0)
april30['date'] = '04-30-2020'
april30['period'] = 1
april30 = april30.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1092]:
may01 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9e26adc2c475d3378d7579e48e936f8a807b254b/by-age.csv?raw=True",index_col=0)
may01['date'] = '05-01-2020'
may01['period'] = 1
may01 = may01.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1093]:
may02 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/946537b1647b4bc7c621716ef6f8e336de09068b/by-age.csv?raw=True",index_col=0)
may02['date'] = '05-02-2020'
may02['period'] = 1
may02 = may02.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1094]:
may03 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/26d8d4c6a64c75608eb9229a41cffbb72a03685d/by-age.csv?raw=True",index_col=0)
may03['date'] = '05-03-2020'
may03['period'] = 1
may03 = may03.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1095]:
may04 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/e9647e089c58884bb8ee5dd4972782c69327e3ee/by-age.csv?raw=True",index_col=0)
may04['date'] = '05-04-2020'
may04['period'] = 1
may04 = may04.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1096]:
may05 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/dbf813f886c2323ac1e161b9aac966e87278ae80/by-age.csv?raw=True",index_col=0)
may05['date'] = '05-05-2020'
may05['period'] = 1
may05 = may05.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1097]:
may06 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d1df026ad726baf9554f3edd246b7495a8cd247f/by-age.csv?raw=True",index_col=0)
may06['date'] = '05-06-2020'
may06['period'] = 2
may06 = may06.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1098]:
may07 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6d7c4a94d6472a9ffc061166d099a4e5d89cd3e3/by-age.csv?raw=True",index_col=0)
may07['date'] = '05-07-2020'
may07['period'] = 2
may07 = may07.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1099]:
may08 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/2dad8ad0c34db78a343a304ee5bcd56cf2a2194b/by-age.csv?raw=True",index_col=0)
may08['date'] = '05-08-2020'
may08['period'] = 2
may08 = may08.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1100]:
may09 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/16f92651e3cd6585df1165e74126258f59f6fb91/by-age.csv?raw=True",index_col=0)
may09['date'] = '05-09-2020'
may09['period'] = 2
may09 = may09.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1101]:
may10 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/257399da1e7e974e9366bf4c5d1d3bfbc6dc9093/by-age.csv?raw=True",index_col=0)
may10['date'] = '05-10-2020'
may10['period'] = 2
may10 = may10.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1102]:
may11 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/5ef81d9009d68a65ef56a27ed2b2b7506952181a/by-age.csv?raw=True",index_col=0)
may11['date'] = '05-11-2020'
may11['period'] = 2
may11 = may11.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1103]:
may12 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6b501e5e4fbe09d49d454e00e18205dd6fec9bff/by-age.csv?raw=True",index_col=0)
may12['date'] = '05-12-2020'
may12['period'] = 2
may12 = may12.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1104]:
may13 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/82ea643906d764faae2da4f9fdd1cdd922d98c73/by-age.csv?raw=True",index_col=0)
may13['date'] = '05-13-2020'
may13['period'] = 3
may13 = may13.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1105]:
may14 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ac5cfc575709dfe8a928a7637e4d5c4ccf33d43d/by-age.csv?raw=True",index_col=0)
may14['date'] = '05-14-2020'
may14['period'] = 3
may14 = may14.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1106]:
may15 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ebe9ba75c55a2f1dcedbfc00396a6dc0873b71c4/by-age.csv?raw=True",index_col=0)
may15['date'] = '05-15-2020'
may15['period'] = 3
may15 = may15.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1107]:
may16 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/25021ca2c2f77589988e750a4024967fa887c85d/by-age.csv?raw=True",index_col=0)
may16['date'] = '05-16-2020'
may16['period'] = 3
may16 = may16.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1108]:
may17 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d9d894ac238333fb90ff44f19ad6bc7ad227eda4/by-age.csv?raw=True",index_col=0)
may17['date'] = '05-17-2020'
may17['period'] = 3
may17 = may17.rename(columns={'COVID_CASE_RATE': 'CASE_RATE', 'HOSPITALIZED_CASE_RATE': 'HOSPITALIZED_RATE', 'DEATH_RATE':'DEATH_RATE'})

In [1109]:
may18 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/50e60ee5c8f36198abc9b697761128dd29f10fc9/by-age.csv?raw=True",index_col=0)
may18['date'] = '05-18-2020'
may18['period'] = 3

In [1110]:
may19 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/a68f42fe3615eaf3d36df219059eb94595cee933/by-age.csv?raw=True",index_col=0)
may19['date'] = '05-19-2020'
may19['period'] = 3

In [1111]:
may20 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/0c4a03c9a39470b49a60eb1456c64fb0df9e08f8/by-age.csv?raw=True",index_col=0)
may20['date'] = '05-20-2020'
may20['period'] = 4

In [1112]:
may21 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d3a18736ecd9589ab4db24f8cdf76fd40b82c661/by-age.csv?raw=True",index_col=0)
may21['date'] = '05-21-2020'
may21['period'] = 4

In [1113]:
may22 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/3cbb3b744ed90befb37ea7680fac3aa7f782bb30/by-age.csv?raw=True",index_col=0)
may22['date'] = '05-22-2020'
may22['period'] = 4

In [1114]:
may23 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/8d88b2c06cf6b65676d58b28979731faa10c193c/by-age.csv?raw=True",index_col=0)
may23['date'] = '05-23-2020'
may23['period'] = 4

In [1115]:
may24 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9332798c68db780365109f156892efc3d9315485/by-age.csv?raw=True",index_col=0)
may24['date'] = '05-24-2020'
may24['period'] = 4

In [1116]:
may25 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f19c0bc29137b7a1c503c09ec0c2b2e08d27d439/by-age.csv?raw=True",index_col=0)
may25['date'] = '05-25-2020'
may25['period'] = 4

In [1117]:
may26 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d52fdfe48dc9b8fe446df048c681b9c19555e469/by-age.csv?raw=True",index_col=0)
may26['date'] = '05-26-2020'
may26['period'] = 4

In [1118]:
may27 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/498a068d6ca1765231b8526a5529ec552a0daff7/by-age.csv?raw=True",index_col=0)
may27['date'] = '05-27-2020'
may27['period'] = 5

In [1119]:
may28 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/65efb1f75b2714bf06fc2e76fba22315727f6943/by-age.csv?raw=True",index_col=0)
may28['date'] = '05-28-2020'
may28['period'] = 5

In [1120]:
may29 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/8636c5557e93e0c5f35b8c2f8ae1ed1e1077d469/by-age.csv?raw=True",index_col=0)
may29['date'] = '05-29-2020'
may29['period'] = 5

In [1121]:
may30 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/3e9a27ce96a59d9107295ade2b2d7255e605b47b/by-age.csv?raw=True",index_col=0)
may30['date'] = '05-30-2020'
may30['period'] = 5

In [1122]:
may31 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9b5cd4d9259587d41017804dda6589a7b2ab5b3c/by-age.csv?raw=True",index_col=0)
may31['date'] = '05-31-2020'
may31['period'] = 5

In [1123]:
june01 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/62444c1cbfda69c28ed468d14be3f332ea35eea7/by-age.csv?raw=True",index_col=0)
june01['date'] = '06-01-2020'
june01['period'] = 5

In [1124]:
june02 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/53f5d7935feb50fe87132c928f45455af4149407/by-age.csv?raw=True",index_col=0)
june02['date'] = '06-02-2020'
june02['period'] = 5

In [1125]:
june03 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/eb3b8e99cb07bb04ff7b73c2d86e45ae68a4aab7/by-age.csv?raw=True",index_col=0)
june03['date'] = '06-03-2020'
june03['period'] = 6

In [1126]:
june04 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f094fb20c7843f218cea3bc47a06ebe8055d6127/by-age.csv?raw=True",index_col=0)
june04['date'] = '06-04-2020'
june04['period'] = 6

In [1127]:
june05 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/582977c6b9e14f048305403e1b830145e0669a5e/by-age.csv?raw=True",index_col=0)
june05['date'] = '06-05-2020'
june05['period'] = 6

In [1128]:
june06 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9e0c1fe569b09ebddbccd6c9f6d519e28920e86a/by-age.csv?raw=True",index_col=0)
june06['date'] = '06-06-2020'
june06['period'] = 6

In [1129]:
june07 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6328e0b130a4dee1f6140ed3aa8264168d2a925f/by-age.csv?raw=True",index_col=0)
june07['date'] = '06-07-2020'
june07['period'] = 6

In [1130]:
june08 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/3f21405a00bf7c93db5a5209b44886882feb30a6/by-age.csv?raw=True",index_col=0)
june08['date'] = '06-08-2020'
june08['period'] = 6

In [1131]:
june09 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/5ecc5d16eeb6f8202c3457bea892cfe8eea5dab9/by-age.csv?raw=True",index_col=0)
june09['date'] = '06-09-2020'
june09['period'] = 6

In [1132]:
june10 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/b820b687f7b032763fbb38b59d79f512dc3971df/by-age.csv?raw=True",index_col=0)
june10['date'] = '06-10-2020'
june10['period'] = 7

In [1133]:
june11 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/b6ae2b94fb0f32283201433147a6f07d0aa14815/by-age.csv?raw=True",index_col=0)
june11['date'] = '06-11-2020'
june11['period'] = 7

In [1134]:
june12 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/b92f6e5cd8d625fba712128a54da8236694c5941/by-age.csv?raw=True",index_col=0)
june12['date'] = '06-12-2020'
june12['period'] = 7

In [1135]:
june13 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9b7a380c44801db4cf3fdd87fe97747542e20e03/by-age.csv?raw=True",index_col=0)
june13['date'] = '06-13-2020'
june13['period'] = 7

In [1136]:
june14 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9913aec646fd3eb47b9a84afaf4db3f231b0c3a9/by-age.csv?raw=True",index_col=0)
june14['date'] = '06-14-2020'
june14['period'] = 7

In [1137]:
june15 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/8ebc7a35f37f2ed2310574ea5b2e4047163c8265/by-age.csv?raw=True",index_col=0)
june15['date'] = '06-15-2020'
june15['period'] = 7

In [1138]:
june16 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/a86f0bf54cf761a0756e99d24fd037c04cb0a2ec/by-age.csv?raw=True",index_col=0)
june16['date'] = '06-16-2020'
june16['period'] = 7

In [1139]:
june17 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/9139cf24bd5501cbdff732f4738930ebf2d21ee4/by-age.csv?raw=True",index_col=0)
june17['date'] = '06-17-2020'
june17['period'] = 8

In [1140]:
june18 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ef7b0a53f3f2007fbc98d201a0bec962af06af42/by-age.csv?raw=True",index_col=0)
june18['date'] = '06-18-2020'
june18['period'] = 8

In [1141]:
june19 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7e6195efe0a081ecdf33a7f2ec003d9230268c12/by-age.csv?raw=True",index_col=0)
june19['date'] = '06-19-2020'
june19['period'] = 8

In [1142]:
june20 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/1e719a7f7e0db540be277d2f6cf18badc3088ee9/by-age.csv?raw=True",index_col=0)
june20['date'] = '06-20-2020'
june20['period'] = 8

In [1143]:
june21 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/deac492572f142ff768b0f377798512b7d71319a/by-age.csv?raw=True",index_col=0)
june21['date'] = '06-21-2020'
june21['period'] = 8

In [1144]:
june22 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/cc87cd44bbae0b365e7ec83d25f9ad5bc6b72778/by-age.csv?raw=True",index_col=0)
june22['date'] = '06-22-2020'
june22['period'] = 8

In [1145]:
june23 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/cf508e8fe08ddff44a847c1b54209c598b88c913/by-age.csv?raw=True",index_col=0)
june23['date'] = '06-23-2020'
june23['period'] = 8

In [1146]:
june24 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/be46b4e48653c29fab890473672cd7d7e0c7e59c/by-age.csv?raw=True",index_col=0)
june24['date'] = '06-24-2020'
june24['period'] = 9

In [1147]:
june25 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/296486db8a787e8da20e73bae33f7705e01fbb6b/by-age.csv?raw=True",index_col=0)
june25['date'] = '06-25-2020'
june25['period'] = 9

In [1148]:
june26 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7e1c437a15155923cdd3661efe3d363feb934be0/by-age.csv?raw=True",index_col=0)
june26['date'] = '06-26-2020'
june26['period'] = 9

In [1149]:
june27 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/5d87847b9fd6da73ff5c1ba03dada0b624b60744/by-age.csv?raw=True",index_col=0)
june27['date'] = '06-27-2020'
june27['period'] = 9

In [1150]:
june28 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f78cda145befd762b6644b2f57fa47bbc9ce92e3/by-age.csv?raw=True",index_col=0)
june28['date'] = '06-28-2020'
june28['period'] = 9

In [1151]:
june30 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/695e5fbdada25273f13b4af024f96e37f8503efc/by-age.csv?raw=True",index_col=0)
june30['date'] = '06-30-2020'
june30['period'] = 9

In [1152]:
july01 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/41f823d90887251735ad4e6f4814548fc9526606/by-age.csv?raw=True",index_col=0)
july01['date'] = '07-01-2020'
july01['period'] = 10

In [1153]:
july02 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/144c474d7b7cb2d2fd1eb7a0c39208453519e311/by-age.csv?raw=True",index_col=0)
july02['date'] = '07-02-2020'
july02['period'] = 10

In [1154]:
july03 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/97b6723d9a02b5f3108b3864ea52627dee92ce68/by-age.csv?raw=True",index_col=0)
july03['date'] = '07-03-2020'
july03['period'] = 10

In [1155]:
july04 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/72af70695f62b928425560ff002edc372141ca81/by-age.csv?raw=True",index_col=0)
july04['date'] = '07-04-2020'
july04['period'] = 10

In [1156]:
july05 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/2232fd908e3e32244bf653e51e7684af9c87970b/by-age.csv?raw=True",index_col=0)
july05['date'] = '07-05-2020'
july05['period'] = 10

In [1157]:
july06 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/eda5f92d1396398f7c0abb72c7d0ce189a374281/by-age.csv?raw=True",index_col=0)
july06['date'] = '07-06-2020'
july06['period'] = 10

In [1158]:
july07 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7132770488c7ef820ab3c3bc9dd22a3dbe5572fe/by-age.csv?raw=True",index_col=0)
july07['date'] = '07-07-2020'
july07['period'] = 10

In [1159]:
july08 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/17e76119fc87a656c9ef3729e5e9ac702894b40b/by-age.csv?raw=True",index_col=0)
july08['date'] = '07-08-2020'
july08['period'] = 11

In [1160]:
july09 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ce5be7225940034f774ab31d0dc09ba54125642f/by-age.csv?raw=True",index_col=0)
july09['date'] = '07-09-2020'
july09['period'] = 11

In [1161]:
july10 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/70cb39a0b8b78433d26dc8f816d61da78fee75f5/by-age.csv?raw=True",index_col=0)
july10['date'] = '07-10-2020'
july10['period'] = 11

In [1162]:
july11 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7ecf2cdd35fe3a7a0c3d4129a9888fd4ca8550ed/by-age.csv?raw=True",index_col=0)
july11['date'] = '07-11-2020'
july11['period'] = 11

In [1163]:
july12 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/4f81f2d5e1b6bcd3f01267ffac4259cda7fae689/by-age.csv?raw=True",index_col=0)
july12['date'] = '07-12-2020'
july12['period'] = 11

In [1164]:
july13 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f9726f4702d598be69987465de64c516a797fec7/by-age.csv?raw=True",index_col=0)
july13['date'] = '07-13-2020'
july13['period'] = 11

In [1165]:
july14 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d3060c1cb1d3afddef722b42c6aa683fb90458e3/by-age.csv?raw=True",index_col=0)
july14['date'] = '07-14-2020'
july14['period'] = 11

In [1166]:
july15 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d9bee1e514769766bfc888c5cf5b56ae7d2fe717/by-age.csv?raw=True",index_col=0)
july15['date'] = '07-15-2020'
july15['period'] = 12

In [1167]:
july16 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/884471b3d7fb96a85a500e7360c3eb3d4593cdf4/by-age.csv?raw=True",index_col=0)
july16['date'] = '07-16-2020'
july16['period'] = 12

In [1168]:
july17 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/732da3899c7995be809c7034d155e643b8234fde/by-age.csv?raw=True",index_col=0)
july17['date'] = '07-17-2020'
july17['period'] = 12

In [1169]:
july18 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/85349ab6bd47414e436873afd7fba6a45bb6ac12/by-age.csv?raw=True",index_col=0)
july18['date'] = '07-18-2020'
july18['period'] = 12

In [1170]:
july19 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/b1a629db5ae84d7277e532b203d655e9532720bb/by-age.csv?raw=True",index_col=0)
july19['date'] = '07-19-2020'
july19['period'] = 12

In [1171]:
july20 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/4613dc2bca155e3136d2e204ad89d64a30f7a334/by-age.csv?raw=True",index_col=0)
july20['date'] = '07-20-2020'
july20['period'] = 12

In [1172]:
july21 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ef6900beea4eac85128cd117dc83d1319191de08/by-age.csv?raw=True",index_col=0)
july21['date'] = '07-21-2020'
july21['period'] = 12

In [1173]:
july22 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6e4171f60a90d5ee309111facbaa278cccb82a86/by-age.csv?raw=True",index_col=0)
july22['date'] = '07-22-2020'
july22['period'] = 'NA'

In [1174]:
july23 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/4270c108e635c67d80af970c4540abdbb003b234/by-age.csv?raw=True",index_col=0)
july23['date'] = '07-23-2020'
july23['period'] = 'NA'

In [1175]:
july24 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/c2539dc70437a42575f3c3ea8b230047de23dff3/by-age.csv?raw=True",index_col=0)
july24['date'] = '07-24-2020'
july24['period'] = 'NA'

In [1176]:
july25 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/fa0817c7d262dce6ebb2efc7d50bc83bf41991ed/by-age.csv?raw=True",index_col=0)
july25['date'] = '07-25-2020'
july25['period'] = 'NA'

In [1177]:
july26 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f7f16ad2ec56552acaa750825238cfb98796cc96/by-age.csv?raw=True",index_col=0)
july26['date'] = '07-26-2020'
july26['period'] = 'NA'

In [1178]:
july27 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ec4a60ebb5eb79970161ff6ac925eaec481ae6a2/by-age.csv?raw=True",index_col=0)
july27['date'] = '07-27-2020'
july27['period'] = 'NA'

In [1179]:
july28 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6daff424410b0e9faef3f33c8c656c5732282f85/by-age.csv?raw=True",index_col=0)
july28['date'] = '07-28-2020'
july28['period'] = 'NA'

In [1180]:
july29 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/18b56f1b5a1dc01fcde42a3243e5102bf8935fae/by-age.csv?raw=True",index_col=0)
july29['date'] = '07-29-2020'
july29['period'] = 'NA'

In [1181]:
july30 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/2bed49841afdd9a9c6b584673b03a901a6ad2140/by-age.csv?raw=True",index_col=0)
july30['date'] = '07-30-2020'
july30['period'] = 'NA'

In [1182]:
july31 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f10021ab793108aad8a25db7a85fa0d722ad7912/by-age.csv?raw=True",index_col=0)
july31['date'] = '07-31-2020'
july31['period'] = 'NA'

In [1183]:
august01 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6a26616a502ae5d02e261262ee155fc20041ee30/by-age.csv?raw=True",index_col=0)
august01['date'] = '08-01-2020'
august01['period'] = 'NA'

In [1184]:
august02 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/a7315f625e7ef4eb15ed326d8ef66a703fccb613/by-age.csv?raw=True",index_col=0)
august02['date'] = '08-02-2020'
august02['period'] = 'NA'

In [1185]:
august03 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/773ffb03e3e4efd32b855f3e31cb113c9e820273/by-age.csv?raw=True",index_col=0)
august03['date'] = '08-03-2020'
august03['period'] = 'NA'

In [1186]:
august04 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/2f12509de24f10a5bdccc02bb79d1ad85538d8aa/by-age.csv?raw=True",index_col=0)
august04['date'] = '08-04-2020'
august04['period'] = 'NA'

In [1187]:
august05 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/b6a811edae7804c31e18e94c8602a73e2938a191/by-age.csv?raw=True",index_col=0)
august05['date'] = '08-05-2020'
august05['period'] = 'NA'

In [1188]:
august06 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/cf02bdfd9dfcf6d5e5d75b9b138b6e727335e9ad/by-age.csv?raw=True",index_col=0)
august06['date'] = '08-06-2020'
august06['period'] = 'NA'

In [1189]:
august07 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/dcdc45973712d6bc15523afaecd27d37d6da305e/by-age.csv?raw=True",index_col=0)
august07['date'] = '08-07-2020'
august07['period'] = 'NA'

In [1190]:
august08 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7c5b81b991c2b5edbf26c237286d497bf869be2c/by-age.csv?raw=True",index_col=0)
august08['date'] = '08-08-2020'
august08['period'] = 'NA'

In [1191]:
august09 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/66105d19d9d1612cba57d904cd90eebde9115704/by-age.csv?raw=True",index_col=0)
august09['date'] = '08-09-2020'
august09['period'] = 'NA'

In [1192]:
august10 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f4f433546d1c2cd2321ac5d3bb51d8689e83d419/by-age.csv?raw=True",index_col=0)
august10['date'] = '08-10-2020'
august10['period'] = 'NA'

In [1193]:
august11 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/5158a16b1c0927a55e08f9d2a6c94279d4a90003/by-age.csv?raw=True",index_col=0)
august11['date'] = '08-11-2020'
august11['period'] = 'NA'

In [1194]:
august12 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/16224c08aeaf5a625785ac4a82137d0369db4e93/by-age.csv?raw=True",index_col=0)
august12['date'] = '08-12-2020'
august12['period'] = 'NA'

In [1195]:
august13 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/5f06bd065ec344111d569b23f29f42e0701eac01/by-age.csv?raw=True",index_col=0)
august13['date'] = '08-13-2020'
august13['period'] = 'NA'

In [1196]:
august14 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/538891f0e2aeeb60b543bb930ea35b6d08f72790/by-age.csv?raw=True",index_col=0)
august14['date'] = '08-14-2020'
august14['period'] = 'NA'

In [1197]:
august15 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/91bd862d71e2d6df81843a5e05510629884ca4d2/by-age.csv?raw=True",index_col=0)
august15['date'] = '08-15-2020'
august15['period'] = 'NA'

In [1198]:
august16 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/a5fecbe9f995723e5a0c4b816a985eaff4789340/by-age.csv?raw=True",index_col=0)
august16['date'] = '08-16-2020'
august16['period'] = 'NA'

In [1199]:
august17 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/0f4f0056ee6de6f2a54b0272c7638f5de46698d2/by-age.csv?raw=True",index_col=0)
august17['date'] = '08-17-2020'
august17['period'] = 'NA'

In [1200]:
august18 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/02b25780056aa1c24d29f307d76d0f188a1b9839/by-age.csv?raw=True",index_col=0)
august18['date'] = '08-18-2020'
august18['period'] = 13

In [1201]:
august19 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/5d654516f35cff33c071f702ba727e0ac1b626e4/by-age.csv?raw=True",index_col=0)
august19['date'] = '08-19-2020'
august19['period'] = 13

In [1202]:
august20 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/647a8213dc537c9fad89162aaf7efd4d77f4a80f/by-age.csv?raw=True",index_col=0)
august20['date'] = '08-20-2020'
august20['period'] = 13

In [1203]:
august21 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/ce3f3a6952914b8222b3f495ccd69a7f3b881e45/by-age.csv?raw=True",index_col=0)
august21['date'] = '08-21-2020'
august21['period'] = 13

In [1204]:
august22 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7e3f387baff20f9cd051a0795a7872f0ab769dcf/by-age.csv?raw=True",index_col=0)
august22['date'] = '08-22-2020'
august22['period'] = 13

In [1205]:
august23 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/96f12eaa412873a96bd4a3ba2721b6f543522a4b/by-age.csv?raw=True",index_col=0)
august23['date'] = '08-23-2020'
august23['period'] = 13

In [1206]:
august24 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/855b4e1f58fb9e989dcb0a5f96a5ecaa64e60151/by-age.csv?raw=True",index_col=0)
august24['date'] = '08-24-2020'
august24['period'] = 13

In [1207]:
august25 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/13daf0b4147ba7a2c0b1064eca9851ce0292c19a/by-age.csv?raw=True",index_col=0)
august25['date'] = '08-25-2020'
august25['period'] = 13

In [1208]:
august26 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/873753a66c9e385232fb6e34038fda1adb3508ce/by-age.csv?raw=True",index_col=0)
august26['date'] = '08-26-2020'
august26['period'] = 13

In [1209]:
august27 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/223542604303441a1879c14421c7debb04c800d0/by-age.csv?raw=True",index_col=0)
august27['date'] = '08-27-2020'
august27['period'] = 13

In [1210]:
august28 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d85359c5a13362536708093a81e9ac72e29e39ed/by-age.csv?raw=True",index_col=0)
august28['date'] = '08-28-2020'
august28['period'] = 13

In [1211]:
august29 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/35ab5bf63970829b63ee14544b46c2ed5982774f/by-age.csv?raw=True",index_col=0)
august29['date'] = '08-29-2020'
august29['period'] = 13

In [1212]:
august30 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/6fa5de80898446c1c651985be0f9d78073667180/by-age.csv?raw=True",index_col=0)
august30['date'] = '08-30-2020'
august30['period'] = 13

In [1213]:
august31 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/bd0a5fe2dd4e768856b64b1d17b295793ae2488f/by-age.csv?raw=True",index_col=0)
august31['date'] = '08-31-2020'
august31['period'] = 13

In [1214]:
sept01 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/7953c97d1e58bbed9934ea04affb12ca74d9c0fb/by-age.csv?raw=True",index_col=0)
sept01['date'] = '09-01-2020'
sept01['period'] = 14

In [1215]:
sept02 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/c1469896916cb2c53e0e1faf3fa571d700602187/by-age.csv?raw=True",index_col=0)
sept02['date'] = '09-02-2020'
sept02['period'] = 14

In [1216]:
sept03 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/f58fbecef084a15f04c9b8ee99c498ee2d54b03b/by-age.csv?raw=True",index_col=0)
sept03['date'] = '09-03-2020'
sept03['period'] = 14

In [1217]:
sept04 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/c7802cf766ae52830403b11edf35a3a895d8d64a/by-age.csv?raw=True",index_col=0)
sept04['date'] = '09-04-2020'
sept04['period'] = 14

In [1218]:
sept05 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/543178026a2531ab3ae9361364c6ae746e44cf65/by-age.csv?raw=True",index_col=0)
sept05['date'] = '09-05-2020'
sept05['period'] = 14

In [1219]:
sept07 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/eac59e5a80628a4aba90460d0cb34c89730532d2/by-age.csv?raw=True",index_col=0)
sept07['date'] = '09-07-2020'
sept07['period'] = 14

In [1220]:
sept08 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/dd51fbe3d9c7fa4add393b051dd88bf95dd6758f/by-age.csv?raw=True",index_col=0)
sept08['date'] = '09-08-2020'
sept08['period'] = 14

In [1221]:
sept09 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/128d24ac2067dba0ad9450dd548be86856b1698d/by-age.csv?raw=True",index_col=0)
sept09['date'] = '09-09-2020'
sept09['period'] = 14

In [1222]:
sept10 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/0eecfe17c3f18db23e7c96224af7316925275904/by-age.csv?raw=True",index_col=0)
sept10['date'] = '09-10-2020'
sept10['period'] = 14

In [1223]:
sept11 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/e79fff6fe7aabfd7c8acd9259b12648b026e7a41/by-age.csv?raw=True",index_col=0)
sept11['date'] = '09-11-2020'
sept11['period'] = 14

In [1224]:
sept12 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/d136fb982ecb454d83e4c2dec9b3bcef9385e392/by-age.csv?raw=True",index_col=0)
sept12['date'] = '09-12-2020'
sept12['period'] = 14

In [1225]:
sept14 = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/3410bae200490807019094e85fe69421036ea938/by-age.csv?raw=True",index_col=0)
sept14['date'] = '09-14-2020'
sept14['period'] = 14

In [1226]:
new_york_hospital_stats = pd.concat([april23,april24,april25,april26,april27,april28,april29,april30,may01,may02,may03,may04,
                                    may05,may06,may07,may08,may09,may10,may11,may12,may13,may14,may15,may16,may17,may18,may19,
                                    may20,may21,may22,may23,may24,may25,may26,may27,may28,may29,may30,may31,june01,june02,june03,
                                    june04,june05,june06,june07,june08,june09,june10,june11,june12,june13,june14,june15,june16,
                                    june17,june18,june19,june20,june21,june22,june23,june24,june25,june26,june27,june28,june30,
                                    july01,july02,july03,july04,july05,july06,july07,july08,july09,july10,july11,july12,july13,
                                    july14,july15,july16,july17,july18,july19,july20,july21,july22,july23,july24,july25,july26,
                                    july27,july28,july29,july30,july31,august01,august02,august03,august04,august05,august06,
                                    august07,august08,august09,august10,august11,august12,august13,august14,august15,august16,
                                    august17,august18,august19,august20,august21,august22,august23,august24,august25,august26,
                                    august27,august28,august29,august30,august31,sept01,sept02,sept03,sept04,sept05,sept07,
                                    sept08,sept09,sept10,sept11,sept12,sept14])

new_york_hospital_stats

,CASE_RATE,HOSPITALIZED_RATE,DEATH_RATE,date,period,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT
AGE_GROUP,,,,,,,,
0-17 years,171.46,13.55,0.23,04-23-2020,1,NaN,NaN,NaN
18-44 years,1554.45,153.69,12.88,04-23-2020,1,NaN,NaN,NaN
45-64 years,2529.03,630.34,113.37,04-23-2020,1,NaN,NaN,NaN
65-74 years,2552.64,1192.50,364.17,04-23-2020,1,NaN,NaN,NaN
75 and older years,2976.74,1830.07,909.18,04-23-2020,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
18-44,2649.15,280.26,21.96,09-14-2020,14,89268.0,9444.0,740.0
45-64,4014.01,929.74,208.17,09-14-2020,14,82530.0,19116.0,4280.0
65-74,3949.98,1790.83,677.42,09-14-2020,14,27615.0,12520.0,4736.0
75+,4735.87,2871.79,1710.32,09-14-2020,14,25904.0,15708.0,9355.0
Citywide,2781.80,683.73,227.70,09-14-2020,14,233636.0,57425.0,19124.0

In [1227]:
new_york_hospital_stats.to_csv('NYC_COVID_GITHUB.csv', index=True)

In [1228]:
ny_final = pd.concat([new_york,new_york_hospital_stats])
ny_final

,phase,indicator,group,state,subgroup,time_period,time_period_label,value,lowci,highci,...,quartile_range,age,CASE_RATE,HOSPITALIZED_RATE,DEATH_RATE,date,period,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT
0,1,Symptoms of Depressive Disorder,By State,New York,New York,1,Apr 23 - May 5,28.7,24.6,33.1,...,24.1 - 28.7,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Symptoms of Anxiety Disorder,By State,New York,New York,1,Apr 23 - May 5,36.1,32.1,40.2,...,31.7 - 37.0,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,1,Apr 23 - May 5,41.4,36.7,46.1,...,36.8 - 41.4,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Symptoms of Depressive Disorder,By State,New York,New York,2,May 7 - May 12,29.2,24.2,34.6,...,25.7 - 35.5,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Symptoms of Anxiety Disorder,By State,New York,New York,2,May 7 - May 12,33,27.7,38.5,...,31.6 - 38.3,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18-44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2649.15,280.26,21.96,09-14-2020,14,89268.0,9444.0,740.0
45-64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4014.01,929.74,208.17,09-14-2020,14,82530.0,19116.0,4280.0
65-74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3949.98,1790.83,677.42,09-14-2020,14,27615.0,12520.0,4736.0
75+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4735.87,2871.79,1710.32,09-14-2020,14,25904.0,15708.0,9355.0
Citywide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2781.80,683.73,227.70,09-14-2020,14,233636.0,57425.0,19124.0

In [1230]:
ny_final.to_csv('NYC_FINAL.csv', index=True)

In [1297]:
#new_york
temp = new_york_hospital_stats.groupby('period').mean()

In [1298]:
temp.reset_index(level=0, inplace=True)
temp = temp.rename(columns={'period': 'time_period'})
temp

,time_period,CASE_RATE,HOSPITALIZED_RATE,DEATH_RATE,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT
0,1,2144.000897,794.878077,301.899744,NaN,NaN,NaN
1,2,2404.179762,884.877857,360.036905,NaN,NaN,NaN
2,3,2553.555000,965.356429,388.187857,63716.833333,16804.833333,5339.833333
3,4,2635.030000,985.732143,405.576905,64791.428571,17004.309524,5458.833333
4,5,2700.058333,1001.279762,415.573333,66455.142857,17289.738095,5591.761905
5,6,2748.899286,1017.878810,423.390952,67691.166667,17599.738095,5695.642857
6,7,2789.700238,1030.960000,430.532143,68669.190476,17831.928571,5790.166667
7,8,2823.529048,1045.095000,435.386667,69538.166667,18099.380952,5856.595238
8,9,2851.057222,1051.672500,442.854722,70282.083333,18217.388889,5956.722222
9,10,2879.245000,1060.274524,460.181429,71075.666667,18377.714286,6185.357143
10,11,2901.934286,1064.758571,463.177857,71776.714286,18470.095238,6222.357143
11,12,2926.734762,1069.078095,465.806429,72548.095238,18556.476190,6256.023810
12,13,3044.419405,1090.545833,471.903690,76154.571429,18984.047619,6341.595238
13,14,3079.854028,1096.361389,473.505972,77246.611111,19094.972222,6363.361111
14,NA,2981.843889,1080.187160,469.480617,74244.425926,18778.555556,6307.018519

In [1358]:
fin = new_york.merge(temp,  on='time_period', how='left')
fin

,phase,indicator,group,state,subgroup,time_period,time_period_label,value,lowci,highci,confidence_interval,quartile_range,age,CASE_RATE,HOSPITALIZED_RATE,DEATH_RATE,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT
0,1,Symptoms of Depressive Disorder,By State,New York,New York,1,Apr 23 - May 5,28.7,24.6,33.1,24.6 - 33.1,24.1 - 28.7,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Symptoms of Anxiety Disorder,By State,New York,New York,1,Apr 23 - May 5,36.1,32.1,40.2,32.1 - 40.2,31.7 - 37.0,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,1,Apr 23 - May 5,41.4,36.7,46.1,36.7 - 46.1,36.8 - 41.4,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Symptoms of Depressive Disorder,By State,New York,New York,2,May 7 - May 12,29.2,24.2,34.6,24.2 - 34.6,25.7 - 35.5,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Symptoms of Anxiety Disorder,By State,New York,New York,2,May 7 - May 12,33,27.7,38.5,27.7 - 38.5,31.6 - 38.3,18 - 29 years,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,2,Symptoms of Anxiety Disorder,By State,New York,New York,13,Aug 19 - Aug 31,29.9,26.9,33.1,26.9 - 33.1,28.5-30.6,80 years and above,NaN,NaN,NaN,NaN,NaN,NaN
290,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,13,Aug 19 - Aug 31,34.4,31.3,37.6,31.3 - 37.6,33.3-35.6,80 years and above,NaN,NaN,NaN,NaN,NaN,NaN
291,2,Symptoms of Depressive Disorder,By State,New York,New York,14,Sep 2 - Sep 14,25.1,21.6,28.8,21.6 - 28.8,23.3-26.5,80 years and above,NaN,NaN,NaN,NaN,NaN,NaN
292,2,Symptoms of Anxiety Disorder,By State,New York,New York,14,Sep 2 - Sep 14,33.5,29.7,37.5,29.7 - 37.5,33.5-36.9,80 years and above,NaN,NaN,NaN,NaN,NaN,NaN
293,2,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,14,Sep 2 - Sep 14,37.7,33.6,41.9,33.6 - 41.9,35.4-38.1,80 years and above,NaN,NaN,NaN,NaN,NaN,NaN

In [1360]:
new_york.to_csv('new_york.csv', index=False)
temp.to_csv('temp.csv',index=False)