In [154]:
import pandas as pd
from sodapy import Socrata

client = Socrata("data.cdc.gov", None)

results = client.get("8pt5-q6wp", limit=3000)

# Convert to pandas DataFrame
df = pd.DataFrame.from_records(results)
df.to_csv('./mental_health.csv')

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [155]:
New_York = df[df['state']=='New York']
New_York

,indicator,group,state,subgroup,week,week_label,value,lowci,highci,confidence_interval,quartile_range
51,Symptoms of Depressive Disorder,By State,New York,New York,1,Apr 23 - May 5,28.7,24.6,33.1,24.6 - 33.1,24.1 - 28.7
121,Symptoms of Anxiety Disorder,By State,New York,New York,1,Apr 23 - May 5,36.1,32.1,40.2,32.1 - 40.2,31.7 - 37.0
191,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,1,Apr 23 - May 5,41.4,36.7,46.1,36.7 - 46.1,36.8 - 41.4
261,Symptoms of Depressive Disorder,By State,New York,New York,2,May 7 - May 12,29.2,24.2,34.6,24.2 - 34.6,25.7 - 35.5
331,Symptoms of Anxiety Disorder,By State,New York,New York,2,May 7 - May 12,33,27.7,38.5,27.7 - 38.5,31.6 - 38.3
401,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,2,May 7 - May 12,36.9,31.6,42.4,31.6 - 42.4,36.1 - 48.4
471,Symptoms of Depressive Disorder,By State,New York,New York,3,May 14 - May 19,23.8,20,28,20.0 - 28.0,23.3-25.6
541,Symptoms of Anxiety Disorder,By State,New York,New York,3,May 14 - May 19,26.8,23.1,30.8,23.1 - 30.8,25.3-27.4
611,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,3,May 14 - May 19,34.9,30.5,39.5,30.5 - 39.5,32.6-34.9
681,Symptoms of Depressive Disorder,By State,New York,New York,4,May 21 - May 26,23.7,20,27.8,20.0 - 27.8,23.0-25.8
751,Symptoms of Anxiety Disorder,By State,New York,New York,4,May 21 - May 26,30.6,26.8,34.5,26.8 - 34.5,28.7-30.6
821,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,4,May 21 - May 26,34.4,30.5,38.5,30.5 - 38.5,33.2-35.5
891,Symptoms of Depressive Disorder,By State,New York,New York,5,May 28 - June 2,24.5,21.3,27.9,21.3 - 27.9,24.4-26.8
961,Symptoms of Anxiety Disorder,By State,New York,New York,5,May 28 - June 2,29.8,26.4,33.4,26.4 - 33.4,29.7-31.7
1031,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,5,May 28 - June 2,34.8,31.6,38.2,31.6 - 38.2,34.3-36.9
1101,Symptoms of Depressive Disorder,By State,New York,New York,6,June 4 - June 9,28.5,24,33.2,24.0 - 33.2,27.3-30.3
1171,Symptoms of Anxiety Disorder,By State,New York,New York,6,June 4 - June 9,36.3,30.9,41.9,30.9 - 41.9,32.8-36.3
1241,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,6,June 4 - June 9,38.6,33.2,44.2,33.2 - 44.2,37.7-40.7
1311,Symptoms of Depressive Disorder,By State,New York,New York,7,June 11 - June 16,23.4,19.6,27.5,19.6 - 27.5,21.8-23.9
1381,Symptoms of Anxiety Disorder,By State,New York,New York,7,June 11 - June 16,28.7,24.3,33.3,24.3 - 33.3,27.4-30.5
1451,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,7,June 11 - June 16,32.9,28.1,37.8,28.1 - 37.8,32.3-34.9
1521,Symptoms of Depressive Disorder,By State,New York,New York,8,June 18 - June 23,24.2,20.8,27.9,20.8 - 27.9,22.5-25.0
1591,Symptoms of Anxiety Disorder,By State,New York,New York,8,June 18 - June 23,26.9,23.6,30.5,23.6 - 30.5,21.3-27.7
1661,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,8,June 18 - June 23,32.9,29.4,36.7,29.4 - 36.7,31.8-34.4
1731,Symptoms of Depressive Disorder,By State,New York,New York,9,June 25 - June 30,23.9,20.6,27.4,20.6 - 27.4,23.9-26.0
1801,Symptoms of Anxiety Disorder,By State,New York,New York,9,June 25 - June 30,30.6,27,34.4,27.0 - 34.4,29.5-32.2
1871,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,9,June 25 - June 30,34.3,30.5,38.3,30.5 - 38.3,34.1-35.9
1941,Symptoms of Depressive Disorder,By State,New York,New York,10,July 2 - July 7,28.5,25,32.1,25.0 - 32.1,26.8-29.3
2011,Symptoms of Anxiety Disorder,By State,New York,New York,10,July 2 - July 7,34.7,30.4,39.2,30.4 - 39.2,33.0-35.3
2081,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,10,July 2 - July 7,39.7,35.4,44,35.4 - 44.0,38.1-40.6
2151,Symptoms of Depressive Disorder,By State,New York,New York,11,July 9 - July 14,25,21.1,29.1,21.1 - 29.1,24.1-27.2
2221,Symptoms of Anxiety Disorder,By State,New York,New York,11,July 9 - July 14,34.2,29.2,39.6,29.2 - 39.6,31.1-34.2
2291,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,11,July 9 - July 14,38.3,33.4,43.5,33.4 - 43.5,34.8-38.3
2361,Symptoms of Depressive Disorder,By State,New York,New York,12,July 16 - July 21,29.3,25.1,33.8,25.1 - 33.8,26.0-29.3
2431,Symptoms of Anxiety Disorder,By State,New York,New York,12,July 16 - July 21,36.2,31.6,41.1,31.6 - 41.1,35.6-38.4
2501,Symptoms of Anxiety Disorder or Depressive Dis...,By State,New York,New York,12,July 16 - July 21,41.1,36,46.4,36.0 - 46.4,40.6-43.5

In [156]:
#Entire city data

borough_covid_count = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/by-boro.csv?raw=true", index_col=0)
age = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/by-age.csv?raw=true",index_col=0)
poverty = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/by-poverty.csv?raw=true", index_col=0)
race = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/by-race.csv?raw=true", index_col=0)
sex = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/by-sex.csv?raw=true",index_col=0)
hospital_cases = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/case-hosp-death.csv?raw=true")
zip_code = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/data-by-modzcta.csv?raw=true", index_col=0)
covid_summary = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/summary.csv?raw=true")
rate_of_hospital_visit = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/syndromic_data.csv?raw=true", index_col=0)
hospital_visit_4weeks = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/syndromic_data_4week.csv?raw=true", index_col=0)
covid_tests = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/tests.csv?raw=true", index_col=0)

In [157]:
#Get data sorted by borough 

borough_age = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/boro/boroughs-by-age.csv?raw=true", index_col=0)
borough_race = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/boro/boroughs-by-race.csv?raw=true", index_col=0)
borough_sex = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/boro/boroughs-by-sex.csv?raw=true", index_col=0)
borough_covid_counts = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/boro/boroughs-case-hosp-death.csv?raw=true", index_col=0)

In [158]:
#Data on Covid antibodies

antibody_age = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/testing/antibody-by-age.csv?raw=true", index_col=0)
antibody_by_boro = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/testing/antibody-by-boro.csv?raw=true", index_col=0)
antibody_zip_code = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/testing/antibody-by-modzcta.csv?raw=true", index_col=0)
antibody_poverty = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/testing/antibody-by-poverty.csv?raw=true", index_col=0)
antibody_sex = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/testing/antibody-by-sex.csv?raw=true", index_col=0)
antibody_by_week = pd.read_csv("https://github.com/nychealth/coronavirus-data/blob/master/testing/antibody-by-week.csv?raw=true", index_col=0)

In [159]:
hospital_cases

,DATE_OF_INTEREST,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT,CASE_COUNT_7DAY_AVG,INCOMPLETE
0,02/29/2020,1,11,0,NaN,NaN
1,03/01/2020,0,4,0,NaN,NaN
2,03/02/2020,0,21,0,NaN,NaN
3,03/03/2020,2,20,0,NaN,NaN
4,03/04/2020,5,22,0,NaN,NaN
...,...,...,...,...,...,...
182,08/29/2020,107,21,2,233.0,6000.0
183,08/30/2020,143,18,4,233.0,6000.0
184,08/31/2020,174,14,2,215.0,6000.0
185,09/01/2020,53,0,3,183.0,6000.0
186,09/02/2020,17,0,0,142.0,6000.0

In [160]:
hospital_cases[hospital_cases['DATE_OF_INTEREST']=="08/29/2020"]

,DATE_OF_INTEREST,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT,CASE_COUNT_7DAY_AVG,INCOMPLETE
182,08/29/2020,107,21,2,233.0,6000.0

In [161]:
age

,CASE_RATE,HOSPITALIZED_RATE,DEATH_RATE,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT
AGE_GROUP,,,,,,
0-17,439.51,36.48,0.69,7590,630,12
18-44,2609.26,278.51,21.72,87924,9385,732
45-64,3981.57,926.29,207.87,81863,19045,4274
65-74,3922.23,1784.39,675.42,27421,12475,4722
75+,4715.75,2861.56,1704.83,25794,15652,9325
Citywide,2751.22,680.92,227.01,231068,57189,19066

In [162]:
Age = age.drop(['Citywide'])

In [163]:
import pandas as pd
Age['Average_Rate'] = (Age['CASE_RATE'] + Age['DEATH_RATE'])

ImportError: cannot import name 'lmap' from 'pandas.compat' (c:\python38\lib\site-packages\pandas\compat\__init__.py)